/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.cliente.InformacionClientesGUI;
import view.modifysede.ObtenerSedeGUI;
/**
 *
 * @author usuario
 */
public class MenuPrincipalGUI extends javax.swing.JFrame {

    //Atributos
    int id_envio;
    String medio_pago="";
    /**
     * Creates new form ConsultaEmpleadosGUI
     */
    public MenuPrincipalGUI() throws SQLException{
        initComponents();
        
        //No olvidar agregar esto para agregarle las animaciones
        this.setLocationRelativeTo(null);
        this.setTitle("Empleados");
        this.setResizable(false);
        
        
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPaqueteria = new javax.swing.JButton();
        lTtitulo = new javax.swing.JLabel();
        lEfectivo = new javax.swing.JLabel();
        btnSedes = new javax.swing.JButton();
        lEfectivo1 = new javax.swing.JLabel();
        lEfectivo2 = new javax.swing.JLabel();
        btnEmpleados = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        lEfectivo3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTextField8.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team_96px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnPaqueteria.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnPaqueteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paquete.png"))); // NOI18N
        btnPaqueteria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPaqueteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaqueteriaActionPerformed(evt);
            }
        });
        jPanel2.add(btnPaqueteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 180, 170));

        lTtitulo.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        lTtitulo.setForeground(new java.awt.Color(238, 112, 82));
        lTtitulo.setText("SECCIONES");
        jPanel2.add(lTtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 170, 30));

        lEfectivo.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        lEfectivo.setForeground(new java.awt.Color(153, 153, 153));
        lEfectivo.setText("PAQUETERIA");
        jPanel2.add(lEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, 30));

        btnSedes.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnSedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empresa.png"))); // NOI18N
        btnSedes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSedesActionPerformed(evt);
            }
        });
        jPanel2.add(btnSedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 180, 170));

        lEfectivo1.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        lEfectivo1.setForeground(new java.awt.Color(153, 153, 153));
        lEfectivo1.setText("SEDES");
        jPanel2.add(lEfectivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, 30));

        lEfectivo2.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        lEfectivo2.setForeground(new java.awt.Color(153, 153, 153));
        lEfectivo2.setText("EMPLEADOS");
        jPanel2.add(lEfectivo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, 30));

        btnEmpleados.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empleados.png"))); // NOI18N
        btnEmpleados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, 170));

        btnReportes.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportar.png"))); // NOI18N
        btnReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 180, 170));

        lEfectivo3.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        lEfectivo3.setForeground(new java.awt.Color(153, 153, 153));
        lEfectivo3.setText("REPORTES");
        jPanel2.add(lEfectivo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaqueteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaqueteriaActionPerformed
        InformacionClientesGUI cliente = new InformacionClientesGUI();
        this.setVisible(false);
        cliente.setVisible(true);
    }//GEN-LAST:event_btnPaqueteriaActionPerformed

    private void btnSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSedesActionPerformed
        ObtenerSedeGUI sedes = new ObtenerSedeGUI();
       this.setVisible(false);
       sedes.setVisible(true);
        
    }//GEN-LAST:event_btnSedesActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        ConsultaEmpleadosGUI consulta = new ConsultaEmpleadosGUI();
        this.setVisible(false);
        consulta.setVisible(true);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //Aqui en el main es importante cambiar donde dice look and feel, de Nimbus a Windows
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuPrincipalGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuPrincipalGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnPaqueteria;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSedes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lEfectivo;
    private javax.swing.JLabel lEfectivo1;
    private javax.swing.JLabel lEfectivo2;
    private javax.swing.JLabel lEfectivo3;
    private javax.swing.JLabel lTtitulo;
    // End of variables declaration//GEN-END:variables
}
