/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.DatosEmpleadosDao;
import model.vo.DatosEmpleados;

/**
 *
 * @author Windows 10
 */
public class PagoEnvio extends javax.swing.JFrame implements Printable
{

    /**
     * Creates new form PagoEnvio
     */
    public PagoEnvio() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsuario6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtipopaquete = new javax.swing.JTextField();
        txvalor = new javax.swing.JTextField();
        txpaquete = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtamano = new javax.swing.JTextField();
        txdestino = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txvalorseguro = new javax.swing.JTextField();
        tximpuesto = new javax.swing.JTextField();
        txcliente = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txidenvio = new javax.swing.JTextField();
        txpeso1 = new javax.swing.JTextField();

        tfUsuario6.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        tfUsuario6.setForeground(new java.awt.Color(153, 153, 153));
        tfUsuario6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsuario6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAGO DE PAQUETE");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team_96px.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        titulo1.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        titulo1.setForeground(new java.awt.Color(238, 112, 82));
        titulo1.setText("PAGO DE ENVIOS");
        jPanel2.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 112, 82));
        jLabel16.setText("Peso de Paquete:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 112, 82));
        jLabel17.setText("Valor de Paquete:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 112, 82));
        jLabel18.setText("# De Paquete:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 30));

        txtipopaquete.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txtipopaquete.setForeground(new java.awt.Color(153, 153, 153));
        txtipopaquete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtipopaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 170, 25));

        txvalor.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txvalor.setForeground(new java.awt.Color(153, 153, 153));
        txvalor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txvalorActionPerformed(evt);
            }
        });
        jPanel2.add(txvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 170, 25));

        txpaquete.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txpaquete.setForeground(new java.awt.Color(153, 153, 153));
        txpaquete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txpaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpaqueteActionPerformed(evt);
            }
        });
        jPanel2.add(txpaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 170, 25));

        jLabel19.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(238, 112, 82));
        jLabel19.setText("Tamaño de Paquete:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        txtamano.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txtamano.setForeground(new java.awt.Color(153, 153, 153));
        txtamano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamanoActionPerformed(evt);
            }
        });
        jPanel2.add(txtamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 170, 25));

        txdestino.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txdestino.setForeground(new java.awt.Color(153, 153, 153));
        txdestino.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txdestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txdestinoActionPerformed(evt);
            }
        });
        jPanel2.add(txdestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 170, 25));

        jLabel20.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(238, 112, 82));
        jLabel20.setText("Identificacion Cliente:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel21.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(238, 112, 82));
        jLabel21.setText("Tipo de Paquete:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel22.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(238, 112, 82));
        jLabel22.setText("Impuesto valor:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel24.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(238, 112, 82));
        jLabel24.setText("Valor del Seguro:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        txvalorseguro.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txvalorseguro.setForeground(new java.awt.Color(153, 153, 153));
        txvalorseguro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txvalorseguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txvalorseguroActionPerformed(evt);
            }
        });
        jPanel2.add(txvalorseguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 170, 25));

        tximpuesto.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        tximpuesto.setForeground(new java.awt.Color(153, 153, 153));
        tximpuesto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tximpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tximpuestoActionPerformed(evt);
            }
        });
        jPanel2.add(tximpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 170, 25));

        txcliente.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txcliente.setForeground(new java.awt.Color(153, 153, 153));
        txcliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txclienteActionPerformed(evt);
            }
        });
        jPanel2.add(txcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 170, 25));

        jLabel25.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(238, 112, 82));
        jLabel25.setText("Identificacion Destino:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("IMPRIMIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("PAGAR ENVIO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        jLabel26.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(238, 112, 82));
        jLabel26.setText("Id_envio:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 30));

        txidenvio.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txidenvio.setForeground(new java.awt.Color(153, 153, 153));
        txidenvio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txidenvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txidenvioActionPerformed(evt);
            }
        });
        jPanel2.add(txidenvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 170, 25));

        txpeso1.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txpeso1.setForeground(new java.awt.Color(153, 153, 153));
        txpeso1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txpeso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 170, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void registrarEnvio(){
        if(txpaquete.getText().length()!=0
                && txidenvio.getText().length()!=0
                && txtamano.getText().length()!=0
                && txtipopaquete.getText().length()!=0
                && txvalor.getText().length()!=0
                && tximpuesto.getText().length()!=0
                && txvalorseguro.getText().length()!=0
                && txcliente.getText().length()!=0
                && txdestino.getText().length()!=0){
                
           
                
                PagoEnvio pagoEnvio= new PagoEnvio();
                
                PagoEnvio.setNopaquete(gettxpaquete().getText());
                PagoEnvio.setid_envio(gettex().getText());
                PagoEnvio.setNombre(getTfNombre().getText());
                PagoEnvio.setNum_cedula(getTfNum_cedula().getText());
                PagoEnvio.setTelefono(getTfTelefono().getText());
                PagoEnvio.setDireccion(getTfDireccion().getText());
                PagoEnvio.setCiudad(getTfCiudad().getText());
                PagoEnvio.setCargo((String) getCbCargo().getSelectedItem());
                PagoEnvio.setId_sede((String)getCbId_sede().getSelectedItem());
                
                
                //Se solicita que se registre un elemento de tipo empleado
                DatosEmpleados empleadoRegistrado = null;
                DatosEmpleadosDao d = new DatosEmpleadosDao();
                
                try {
                    empleadoRegistrado = d.registrarEmpleado(nuevoEmpleado);
                    this.setVisible(false);
                    ConsultaEmpleadosGUI consulta = new ConsultaEmpleadosGUI();
                    consulta.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegistroEmpleadosGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                //Reportar exito de la accion
                if(empleadoRegistrado != null){
                    JOptionPane.showMessageDialog(null, "El empleado se registró correctamente");
                }else{
                    JOptionPane.showMessageDialog(null, "No se completó el registro");
                }
                
            
        }else{
            JOptionPane.showMessageDialog(null, "No pueden haber elementos vacios");
        }
    }
    
    private void tfUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsuario6ActionPerformed

    private void txvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txvalorActionPerformed

    private void txpaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpaqueteActionPerformed

    private void txtamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamanoActionPerformed

    private void txdestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txdestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txdestinoActionPerformed

    private void txvalorseguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txvalorseguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txvalorseguroActionPerformed

    private void tximpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tximpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tximpuestoActionPerformed

    private void txclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txclienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            PrinterJob pag = PrinterJob.getPrinterJob();
            pag.setPrintable(this);
            boolean gap = pag.printDialog();
            if(gap)
            {
                pag.print();
            }
        }
        catch (PrinterException pex)
        {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txidenvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txidenvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txidenvioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoEnvio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfUsuario6;
    private javax.swing.JLabel titulo1;
    private javax.swing.JTextField txcliente;
    private javax.swing.JTextField txdestino;
    private javax.swing.JTextField txidenvio;
    private javax.swing.JTextField tximpuesto;
    private javax.swing.JTextField txpaquete;
    private javax.swing.JTextField txpeso1;
    private javax.swing.JTextField txtamano;
    private javax.swing.JTextField txtipopaquete;
    private javax.swing.JTextField txvalor;
    private javax.swing.JTextField txvalorseguro;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        if (index>0)
        { 
                return NO_SUCH_PAGE;
        }
        Graphics2D hub  = (Graphics2D) graf;
        hub.translate(pagfor.getImageableX() * 30, pagfor.getImageableY()* 30 );
        hub.scale(1.0, 1.0);
         
        jPanel2.printAll(graf);
        return PAGE_EXISTS;
        }
    }
