/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.envio;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.DatosEnviosDao;
import model.dao.DatosPagosDao;
import model.vo.DatosEnvios;
import model.vo.DatosPagos;
import view.ModificacionEmpleadosGUI;
import view.paquete.MenuPaquetesGUI;
/**
 *
 * @author usuario
 */
public class MedioPagoGUI extends javax.swing.JFrame {

    //Atributos
    int id_envio;
    String medio_pago="";
    /**
     * Creates new form ConsultaEmpleadosGUI
     */
    public MedioPagoGUI() throws SQLException{
        initComponents();
        consultarIdEnvio();
        
        //No olvidar agregar esto para agregarle las animaciones
        this.setLocationRelativeTo(null);
        this.setTitle("Empleados");
        this.setResizable(false);
        
        
    }  
    
    public void consultarIdEnvio() throws SQLException{
        DatosEnviosDao c = new DatosEnviosDao();
        
        //Este objeto es el que tiene los datos de la base de datos pero para la verificacion
        ArrayList<DatosEnvios> lista = c.consultaMedioPago();
        
        //El objeto se covierte a un arreglo usando el metodo de esta clase el cual recibe el arraylist del tipo consultaEmpleados y el numero de columnas
        id_envio=lista.get(0).getId_envio();
    }
    
    public void registrarPago(){
        
        DatosPagos nuevoPago = new DatosPagos(id_envio, medio_pago);
        
        //Se solicita que se registre un elemento de tipo empleado
        DatosPagos pagoRegistrado = null;
        DatosPagosDao d = new DatosPagosDao();

        try {
            pagoRegistrado = d.registrarPago(nuevoPago);
            this.setVisible(false);
            if(medio_pago.equals("Efectivo")){
                EfectivoGUI consulta = new EfectivoGUI();
            consulta.setVisible(true);
            }else{
                TarjetaGUI consulta = new TarjetaGUI();
                consulta.setVisible(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MedioPagoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Reportar exito de la accion
        if(pagoRegistrado == null){
            JOptionPane.showMessageDialog(null, "No se completó el registro");
        }
               
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEfectivo = new javax.swing.JButton();
        lTtitulo = new javax.swing.JLabel();
        lEfectivo = new javax.swing.JLabel();
        btnTarjeta = new javax.swing.JButton();
        lEfectivo1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTextField8.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(238, 112, 82));
        jLabel15.setText("Atrás");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_64px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team_96px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnEfectivo.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/efectivo.png"))); // NOI18N
        btnEfectivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 180, 170));

        lTtitulo.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        lTtitulo.setForeground(new java.awt.Color(238, 112, 82));
        lTtitulo.setText("SELECCIONE MÉTODO DE PAGO");
        jPanel2.add(lTtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 450, 30));

        lEfectivo.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        lEfectivo.setForeground(new java.awt.Color(153, 153, 153));
        lEfectivo.setText("EFECTIVO");
        jPanel2.add(lEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 30));

        btnTarjeta.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tarjetas-de-credito.png"))); // NOI18N
        btnTarjeta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });
        jPanel2.add(btnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 180, 170));

        lEfectivo1.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        lEfectivo1.setForeground(new java.awt.Color(153, 153, 153));
        lEfectivo1.setText("TARJETA");
        jPanel2.add(lEfectivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivoActionPerformed
        medio_pago="Efectivo";
        registrarPago();
        try {
            EfectivoGUI efectivo = new EfectivoGUI();
            this.setVisible(false);
            efectivo.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MedioPagoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEfectivoActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        MenuPaquetesGUI menu = new MenuPaquetesGUI();
        this.setVisible(false);
        menu.setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        medio_pago="Tarjeta";
        registrarPago();
        TarjetaGUI tarjeta;
        try {
            tarjeta = new TarjetaGUI();
            this.setVisible(false);
            tarjeta.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MedioPagoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //Aqui en el main es importante cambiar donde dice look and feel, de Nimbus a Windows
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedioPagoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedioPagoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedioPagoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedioPagoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MedioPagoGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MedioPagoGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEfectivo;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lEfectivo;
    private javax.swing.JLabel lEfectivo1;
    private javax.swing.JLabel lTtitulo;
    // End of variables declaration//GEN-END:variables
}
