/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.modifysede;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.dao.DatosEmpleadosDao;
import model.dao.DatosSedesDao;
import model.vo.DatosEmpleados;
import model.vo.DatosSedes;
import util.JDBCUtilities;
import view.ModificacionEmpleadosGUI;
import view.RegistroEmpleadosGUI;
import view.modifyempleado.UsuarioGUI;

/**
 *
 * @author Windows 10
 */
public class DireccionGUI extends javax.swing.JFrame {
   

    public DireccionGUI() {
        initComponents();
        obtenerSedes();

      }  
    public void actualizarDireccion() throws SQLException{
        
        if( TfConfirmarDir.getText().length()!=0){
              
                
            DatosSedes direccionActualizar = new DatosSedes();

         
            direccionActualizar.setDireccion_sede(TfConfirmarDir.getText());
            direccionActualizar.setId_sede(Integer.parseInt(cbId_sede.getSelectedItem().toString()));

            DatosSedes sedeActualizada =null;
            DatosSedesDao d = new DatosSedesDao();

            sedeActualizada = d.modificarDireccionSede(direccionActualizar);

            if(sedeActualizada != null){
                JOptionPane.showMessageDialog(null, "La direccion de la sede se actualizó correctamente");
                this.setVisible(false);
                SedeGUI modificacion = new SedeGUI();
                modificacion.setVisible(true);

            }else{
                JOptionPane.showMessageDialog(null, "No se completó la actualización de datos");
            }
        }else{
            JOptionPane.showMessageDialog(null, " Los datos no pueden estar vacios");
        }    
    }
    
    
    public String[][] formatoRegistros(ArrayList<DatosEmpleados> consulta){
        
        //Declaración del contenedor de retorno
        String[][] registros = new String[consulta.size()][2];        

        //Desenvolver los objetos de la colección
        for (int i = 0; i < consulta.size(); i++) {
            registros[i][0] = consulta.get(i).getUsuario();
            registros[i][1] = consulta.get(i).getContrasenia();   
        }

        //Retornar registros en formato JTable
        return registros;

    }
    
    
    private void obtenerSedes() { 
        Connection conexion = null;
        JDBCUtilities conex = new JDBCUtilities();
        ArrayList<Integer> listaSedes = new ArrayList<>();
        try {
            conexion= conex.getConnection();
            Statement leer = conexion.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT id_sede FROM sede");
            while(resultado.next()){
                listaSedes.add(resultado.getInt(1));
            }
            for(int i=0;i<listaSedes.size();i++){
                cbId_sede.addItem(Integer.toString(listaSedes.get(i)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistroEmpleadosGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TfConfirmarDir = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cbId_sede = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team_96px.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        titulo1.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        titulo1.setForeground(new java.awt.Color(238, 112, 82));
        titulo1.setText("MODIFICAR DIRECCION DE UNA SEDE ");
        jPanel2.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 112, 82));
        jLabel17.setText("Confirmar direccion:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        TfConfirmarDir.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        TfConfirmarDir.setForeground(new java.awt.Color(153, 153, 153));
        TfConfirmarDir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TfConfirmarDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfConfirmarDirActionPerformed(evt);
            }
        });
        jPanel2.add(TfConfirmarDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 170, 25));

        titulo.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(153, 153, 153));
        titulo.setText("Llena los siguientes campos para modificar: ");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        jButton1.setText("ATRÁS");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        btnRegistrar1.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnRegistrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnRegistrar1.setText("Modificar Sede");
        btnRegistrar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 200, 50));

        jLabel19.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(238, 112, 82));
        jLabel19.setText("ID Sede:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 30));

        cbId_sede.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        cbId_sede.setForeground(new java.awt.Color(153, 153, 153));
        cbId_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbId_sedeActionPerformed(evt);
            }
        });
        jPanel2.add(cbId_sede, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 170, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       SedeGUI a = new SedeGUI();
      a.setVisible(true);
      this.setVisible(false);
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
    JOptionPane.showMessageDialog( this , "¿Esta seguro de hacer el cambio de sede?", "Modificar Sede" , JOptionPane.INFORMATION_MESSAGE);
        try {
             actualizarDireccion();
        } catch (SQLException ex) {
            Logger.getLogger(CuidadGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void TfConfirmarDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfConfirmarDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfConfirmarDirActionPerformed

    private void cbId_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbId_sedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbId_sedeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DireccionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DireccionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DireccionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DireccionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DireccionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfConfirmarDir;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JComboBox<String> cbId_sede;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables

   
}


